spring.application.name=jobmarket

spring.datasource.url=jdbc:mysql://mysql-3a91e866-jobmarket.c.aivencloud.com:13723/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

tuanjobmarket.jwt.base64-secret=${JWT_SECRET}
tuanjobmarket.jwt.access-token-validity-in-seconds=86400000
tuanjobmarket.refresh-token-validity-in-seconds=86400

spring.data.web.pageable.one-indexed-parameters=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
tuanjobmarket.upload-file.base-path=file:///tmp/upload/

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

MYSQL_PASSWORD    = (password Aiven)
JWT_SECRET        = ODcxODJl...  (giá trị cũ)
MAIL_USERNAME     = courselearn552@gmail.com
MAIL_PASSWORD     = ucvotoajnawlsyef

spring.jpa.defer-datasource-initialization=true
server.port=8080
server.address=0.0.0.0